config/routes.rb
Rails.application.routes.draw do
  get '/users/info', to: 'users#info'
  devise_for :users

  root to: "home#index"

  resources :publications, only: [:index, :show]

  namespace :admin do
    resources :publications
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :subscription

  after_create :create_subscription
  def create_subscription
    Subscription.create(user_id: id) if subscription.nil?
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController
  before_action :find_publication, only: [:show, :edit, :update, :destroy]

  def index
    @publications = Publication.all
  end

  def show

  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)
    if @publication.save
      redirect_to admin_publication_path(@publication)
    else
      render :new, alert: 'Something went wrong'
    end
  end

  def edit

  end

  def update
    if @publication.update(publication_params)
      redirect_to admin_publication_path(@publication)
    else
      render :edit, alert: 'Something went wrong'
    end
  end

  def destroy
    @publication.destroy
    redirect_to admin_publication_path, alert: 'Succesfully deleted publication'
  end

  private

  def find_publication
    @publication = Publication.find(params[:id])
  end

  def publication_params
    params.require(:publication).permit(:title, :description, :file_url)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_for_admin

  def check_for_admin
    if current_user.nil? || !current_user.is_admin?
      redirect_to root_path, alert: 'You must be an administrator to access this path.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all
  end

  def show
    @publications = Publication.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def info
    @subscription = current_user.subscription
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/publications/edit.html.erb
<h3>Edit <%= @publication.title %></h3>
<%= form_for @publication, url: admin_publication_path(@publication) do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label>
    <%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update publication', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/publications/index.html.erb
<h2>Publications</h2>

<div>
  <%= link_to 'New publication', new_admin_publication_path, class: 'btn btn-primary' %>
</div>

<% @publications.each do |publication| %>
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h3 class="card-title"><%= publication.title %></h3>
    </div>
    <div class="card-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <%= link_to "View more details", admin_publication_path(publication), class: "card-link" %>
    <%= link_to "Edit", edit_admin_publication_path(publication), class: "card-link" %>
  </div>
<% end %>

app/views/admin/publications/new.html.erb
<h3>New Publication</h3>
<%= form_for @publication, url: admin_publications_path do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label>
    <%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create publication', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/publications/show.html.erb
<div class="card">
  <div class="card-header bg-secondary text-white">
    <h3 class="card-title"><%= @publication.title %></h3>
  </div>
  <div class="card-body">
    <p><%= @publication.description %></p>
    <p><%= @publication.file_url %></p>
  </div>
</div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Subscription app test with Stripe</a>
  <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
    <ul class="navbar-nav ml-md-auto">
      <% if user_signed_in? %>
        <li class="nav-item active nav_link">
          <%= link_to current_user.email, users_info_path %><
        </li>
        <li class="nav-item active nav-link">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item active nav-link">
          <%= link_to "Log in", new_user_session_path %>
        </li>
        <li class="nav-item active nav-link">
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/publications/index.html.erb
<h2>Publications</h2>

<% @publications.each do |publication| %>
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h3 class="card-title"><%= publication.title %></h3>
    </div>
    <div class="card-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <%= link_to "View more details", publication_path(publication), class: "card-link" %>
  </div>
<% end %>

app/views/publications/show.html.erb
<div class="card">
  <div class="card-header bg-secondary text-white">
    <h3 class="card-title"><%= @publications.title %></h3>
  </div>
  <div class="card-body">
    <p><%= @publications.description %></p>
    <p><%= @publications.file_url %></p>
  </div>
</div>

app/views/users/_form.html.erb
<script src="https://js.stripe.com/v3/"></script>

<form action="/charge" method="post" id="payment-form">
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>

app/views/users/info.html.erb
<%= current_user.email %>
<% if @subscription.active %>
Subscribed
<% else %>
  <%= render 'form' %>
<% end %>